### ISSUE TITLE
WOW, this is great, will you develop it further for 2.80? I don't manage to install it

### ISSUE THREAD

**Issue by sebababi** [TheDuckCow/pose-tools#2]
Hello Patrick,

WOW, this is such an important ADDON, will you develop it further for 2.80? 

I don't manage to install it in 2.80, I also tried to place the unzipped files in the blender/addons folder, but 2.8 doesn't even seem to recognize it. So, it doesn't even show up in the addons preferences list.

Any ideas?
Thanks in advanced

Sebastian

**Comment by TheDuckCow** [comment]
Hi there! Glad you like the addon. It has not yet been updated for Blender 2.8 so it won't work there, but is something I can work on in the near future.

**Comment by TheDuckCow** [comment]
Realize this is long overdue, but initial support for blender 2.8 is now available (but there is a memory issue to be addressed, so be advised on a planned additional update).
